#ifndefMAP_H_INCLUDED
#defineMAP_H_INCLUDED
typedefstruct{
char*key;
char*value;
}stringpair;
typedefstruct{
unsignedintmapSize;
unsignedintmaxSize;
stringpair*pairs;
}mapstruct;
typedefmapstruct*Map;
MapcreateMap(unsignedintmaxSize);
voidfreeMap(MapcurrentMap);
intcontainsKey(MapaMap,char*searchKey);
char*lookupIndex(MapaMap,intindex);
char*lookupKey(MapaMap,char*searchKey);
intinsertKey(MapaMap,char*key,char*value);
#endif
